# server:
#   port:
#     8080
# spring:
#   datasource:
#     username: root
#     password: admin
#     url: jdbc:mysql://localhost:3306/hotel_db
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update